// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: example_service/error_reason.proto

package example_pb

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务错误定义
// 枚举值为业务错误码
// errors.code为http错误码
type ErrorReason int32

const (
	ErrorReason_NONE ErrorReason = 0 // 成功
	// 用户不存在
	ErrorReason_USER_NOT_FOUND ErrorReason = 404
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "NONE",
		404: "USER_NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"NONE":           0,
		"USER_NOT_FOUND": 404,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_example_service_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_example_service_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_example_service_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_example_service_error_reason_proto protoreflect.FileDescriptor

var file_example_service_error_reason_proto_rawDesc = []byte{
	0x0a, 0x22, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x3e, 0x0a, 0x0b, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0xc8, 0x01, 0x12, 0x19, 0x0a, 0x0e, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x94, 0x03, 0x1a, 0x04,
	0xa8, 0x45, 0x94, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x67, 0x67, 0x65, 0x72, 0x7a,
	0x68, 0x75, 0x61, 0x6e, 0x67, 0x31, 0x39, 0x39, 0x34, 0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73,
	0x2d, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_service_error_reason_proto_rawDescOnce sync.Once
	file_example_service_error_reason_proto_rawDescData = file_example_service_error_reason_proto_rawDesc
)

func file_example_service_error_reason_proto_rawDescGZIP() []byte {
	file_example_service_error_reason_proto_rawDescOnce.Do(func() {
		file_example_service_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_service_error_reason_proto_rawDescData)
	})
	return file_example_service_error_reason_proto_rawDescData
}

var file_example_service_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_service_error_reason_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: example_service.ErrorReason
}
var file_example_service_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_service_error_reason_proto_init() }
func file_example_service_error_reason_proto_init() {
	if File_example_service_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_service_error_reason_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_service_error_reason_proto_goTypes,
		DependencyIndexes: file_example_service_error_reason_proto_depIdxs,
		EnumInfos:         file_example_service_error_reason_proto_enumTypes,
	}.Build()
	File_example_service_error_reason_proto = out.File
	file_example_service_error_reason_proto_rawDesc = nil
	file_example_service_error_reason_proto_goTypes = nil
	file_example_service_error_reason_proto_depIdxs = nil
}
