// Code generated by protoc-gen-kratos-foundation-errors. DO NOT EDIT.

package example_pb

import (
	fmt "fmt"
	errors "github.com/jaggerzhuang1994/kratos-foundation/pkg/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 成功
func IsNone(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 200 && e.Reason == "NONE" && e.Metadata != nil && e.Metadata["reason_code"] == "0"
}

// 成功
func ErrorNone(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "成功"
	}
	return errors.New(200, "NONE", fmt.Sprintf(format, args...)).WithReasonCode(0).WithErrStack(4)
}

// 用户不存在
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 404 && e.Reason == "USER_NOT_FOUND" && e.Metadata != nil && e.Metadata["reason_code"] == "404"
}

// 用户不存在
func ErrorUserNotFound(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]
	} else { // 如果没有传参数，则默认填充注释为错误原因
		format = "用户不存在"
	}
	return errors.New(404, "USER_NOT_FOUND", fmt.Sprintf(format, args...)).WithReasonCode(404).WithErrStack(4)
}
