// Code generated by protoc-gen-kratos-foundation-client. DO NOT EDIT.
// versions:
// - protoc-gen-kratos-foundation-client v0.0.0-20260122092019-40b707662381
// - protoc               v4.25.2
// source: example_service/example_service.proto
package example_pb

import (
	context "context"
	wire "github.com/google/wire"
	client "github.com/jaggerzhuang1994/kratos-foundation/pkg/client"
	errors "github.com/pkg/errors"
)

// ExampleServiceApiProvider .
var ExampleServiceApiProvider = wire.NewSet(
	NewExampleServiceApiWrapper,
	wire.Bind(new(ExampleServiceApi), new(*ExampleServiceApiWrapper)),
)

// service interface

// ExampleServiceApi .
type ExampleServiceApi interface {
	// GetUser .
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// GetUser2 .
	GetUser2(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// GetUser3 .
	GetUser3(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// GetUser4 .
	GetUser4(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// impl

// ExampleServiceApiWrapper .
type ExampleServiceApiWrapper struct {
	factory client.Factory
}

var _ ExampleServiceApi = (*ExampleServiceApiWrapper)(nil)

// NewExampleServiceApiWrapper .
func NewExampleServiceApiWrapper(factory client.Factory) *ExampleServiceApiWrapper {
	return &ExampleServiceApiWrapper{factory}
}

// GetUser .
func (c *ExampleServiceApiWrapper) GetUser(ctx context.Context, in *GetUserRequest) (rsp *GetUserResponse, err error) {
	ctx = client.WithDefaultConnName(ctx, "example_service")

	// 获取连接
	httpClient, grpcClient, err := c.factory.ResolveClient(ctx)
	if err != nil {
		return nil, errors.WithMessagef(err, "resolve %s client err", client.ConnNameFromContext(ctx))
	}

	// 发起请求
	if grpcClient != nil {
		opts := client.GrpcCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceClient(grpcClient).GetUser(ctx, in, opts...)
	} else {
		opts := client.HttpCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceHTTPClient(httpClient).GetUser(ctx, in, opts...)
	}
	return
}

// GetUser2 .
func (c *ExampleServiceApiWrapper) GetUser2(ctx context.Context, in *GetUserRequest) (rsp *GetUserResponse, err error) {
	ctx = client.WithDefaultConnName(ctx, "example_service")

	// 获取连接
	httpClient, grpcClient, err := c.factory.ResolveClient(ctx)
	if err != nil {
		return nil, errors.WithMessagef(err, "resolve %s client err", client.ConnNameFromContext(ctx))
	}

	// 发起请求
	if grpcClient != nil {
		opts := client.GrpcCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceClient(grpcClient).GetUser2(ctx, in, opts...)
	} else {
		opts := client.HttpCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceHTTPClient(httpClient).GetUser2(ctx, in, opts...)
	}
	return
}

// GetUser3 .
func (c *ExampleServiceApiWrapper) GetUser3(ctx context.Context, in *GetUserRequest) (rsp *GetUserResponse, err error) {
	ctx = client.WithDefaultConnName(ctx, "example_service")

	// 获取连接
	httpClient, grpcClient, err := c.factory.ResolveClient(ctx)
	if err != nil {
		return nil, errors.WithMessagef(err, "resolve %s client err", client.ConnNameFromContext(ctx))
	}

	// 发起请求
	if grpcClient != nil {
		opts := client.GrpcCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceClient(grpcClient).GetUser3(ctx, in, opts...)
	} else {
		opts := client.HttpCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceHTTPClient(httpClient).GetUser3(ctx, in, opts...)
	}
	return
}

// GetUser4 .
func (c *ExampleServiceApiWrapper) GetUser4(ctx context.Context, in *GetUserRequest) (rsp *GetUserResponse, err error) {
	ctx = client.WithDefaultConnName(ctx, "example_service")

	// 获取连接
	httpClient, grpcClient, err := c.factory.ResolveClient(ctx)
	if err != nil {
		return nil, errors.WithMessagef(err, "resolve %s client err", client.ConnNameFromContext(ctx))
	}

	// 发起请求
	if grpcClient != nil {
		opts := client.GrpcCallOptionFromContext(ctx)
		rsp, err = NewExampleServiceClient(grpcClient).GetUser4(ctx, in, opts...)
	} else {
		_ = httpClient
		panic("not implemented")
	}
	return
}
