// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: example_service/example_service.proto

package example_pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_example_service_example_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_example_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_example_service_example_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetUserResponse_Data  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_example_service_example_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_example_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_example_service_example_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserResponse) GetData() *GetUserResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse_Data) Reset() {
	*x = GetUserResponse_Data{}
	mi := &file_example_service_example_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse_Data) ProtoMessage() {}

func (x *GetUserResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_example_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse_Data.ProtoReflect.Descriptor instead.
func (*GetUserResponse_Data) Descriptor() ([]byte, []int) {
	return file_example_service_example_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetUserResponse_Data) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_example_service_example_service_proto protoreflect.FileDescriptor

const file_example_service_example_service_proto_rawDesc = "" +
	"\n" +
	"%example_service/example_service.proto\x12\x0fexample_service\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa6\x01\n" +
	"\x0fGetUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.example_service.GetUserResponse.DataR\x04data\x1a*\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xfc\x02\n" +
	"\x0eExampleService\x12[\n" +
	"\aGetUser\x12\x1f.example_service.GetUserRequest\x1a .example_service.GetUserResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/user\x12]\n" +
	"\bGetUser2\x12\x1f.example_service.GetUserRequest\x1a .example_service.GetUserResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/user2\x12]\n" +
	"\bGetUser3\x12\x1f.example_service.GetUserRequest\x1a .example_service.GetUserResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/user3\x12O\n" +
	"\bGetUser4\x12\x1f.example_service.GetUserRequest\x1a .example_service.GetUserResponse\"\x00BbZ`github.com/jaggerzhuang1994/kratos-foundation-template/api/example_service/example_pb;example_pbb\x06proto3"

var (
	file_example_service_example_service_proto_rawDescOnce sync.Once
	file_example_service_example_service_proto_rawDescData []byte
)

func file_example_service_example_service_proto_rawDescGZIP() []byte {
	file_example_service_example_service_proto_rawDescOnce.Do(func() {
		file_example_service_example_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_service_example_service_proto_rawDesc), len(file_example_service_example_service_proto_rawDesc)))
	})
	return file_example_service_example_service_proto_rawDescData
}

var file_example_service_example_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_service_example_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),       // 0: example_service.GetUserRequest
	(*GetUserResponse)(nil),      // 1: example_service.GetUserResponse
	(*GetUserResponse_Data)(nil), // 2: example_service.GetUserResponse.Data
}
var file_example_service_example_service_proto_depIdxs = []int32{
	2, // 0: example_service.GetUserResponse.data:type_name -> example_service.GetUserResponse.Data
	0, // 1: example_service.ExampleService.GetUser:input_type -> example_service.GetUserRequest
	0, // 2: example_service.ExampleService.GetUser2:input_type -> example_service.GetUserRequest
	0, // 3: example_service.ExampleService.GetUser3:input_type -> example_service.GetUserRequest
	0, // 4: example_service.ExampleService.GetUser4:input_type -> example_service.GetUserRequest
	1, // 5: example_service.ExampleService.GetUser:output_type -> example_service.GetUserResponse
	1, // 6: example_service.ExampleService.GetUser2:output_type -> example_service.GetUserResponse
	1, // 7: example_service.ExampleService.GetUser3:output_type -> example_service.GetUserResponse
	1, // 8: example_service.ExampleService.GetUser4:output_type -> example_service.GetUserResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_service_example_service_proto_init() }
func file_example_service_example_service_proto_init() {
	if File_example_service_example_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_service_example_service_proto_rawDesc), len(file_example_service_example_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_service_example_service_proto_goTypes,
		DependencyIndexes: file_example_service_example_service_proto_depIdxs,
		MessageInfos:      file_example_service_example_service_proto_msgTypes,
	}.Build()
	File_example_service_example_service_proto = out.File
	file_example_service_example_service_proto_goTypes = nil
	file_example_service_example_service_proto_depIdxs = nil
}
