// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.2
// source: example_service/example_service.proto

package example_pb

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationExampleServiceGetUser = "/example_service.ExampleService/GetUser"
const OperationExampleServiceGetUser2 = "/example_service.ExampleService/GetUser2"
const OperationExampleServiceGetUser3 = "/example_service.ExampleService/GetUser3"

type ExampleServiceHTTPServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUser2(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUser3(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterExampleServiceHTTPServer(s *http.Server, srv ExampleServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/user", _ExampleService_GetUser0_HTTP_Handler(srv))
	r.GET("/user2", _ExampleService_GetUser20_HTTP_Handler(srv))
	r.GET("/user3", _ExampleService_GetUser30_HTTP_Handler(srv))
}

func _ExampleService_GetUser0_HTTP_Handler(srv ExampleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExampleServiceGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserResponse)
		return ctx.Result(200, reply)
	}
}

func _ExampleService_GetUser20_HTTP_Handler(srv ExampleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExampleServiceGetUser2)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser2(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserResponse)
		return ctx.Result(200, reply)
	}
}

func _ExampleService_GetUser30_HTTP_Handler(srv ExampleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExampleServiceGetUser3)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser3(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserResponse)
		return ctx.Result(200, reply)
	}
}

type ExampleServiceHTTPClient interface {
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *GetUserResponse, err error)
	GetUser2(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *GetUserResponse, err error)
	GetUser3(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *GetUserResponse, err error)
}

type ExampleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewExampleServiceHTTPClient(client *http.Client) ExampleServiceHTTPClient {
	return &ExampleServiceHTTPClientImpl{client}
}

func (c *ExampleServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*GetUserResponse, error) {
	var out GetUserResponse
	pattern := "/user"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExampleServiceGetUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ExampleServiceHTTPClientImpl) GetUser2(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*GetUserResponse, error) {
	var out GetUserResponse
	pattern := "/user2"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExampleServiceGetUser2))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ExampleServiceHTTPClientImpl) GetUser3(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*GetUserResponse, error) {
	var out GetUserResponse
	pattern := "/user3"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExampleServiceGetUser3))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
