// Code generated by protoc-gen-kratos-foundation-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/jaggerzhuang1994/kratos-foundation/pkg/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsGreeterUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "GREETER_UNSPECIFIED" && e.Metadata != nil && e.Metadata["reason_code"] == "0"
}

func ErrorGreeterUnspecified(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]

	}
	return errors.New(500, "GREETER_UNSPECIFIED", fmt.Sprintf(format, args...)).WithReasonCode(0).WithErrStack()
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	if e == nil {
		return false
	}
	return e.Code == 500 && e.Reason == "USER_NOT_FOUND" && e.Metadata != nil && e.Metadata["reason_code"] == "1"
}

func ErrorUserNotFound(formatAndArgs ...any) *errors.Error {
	var format string
	var args []any
	if len(formatAndArgs) > 0 {
		format = formatAndArgs[0].(string)
		args = formatAndArgs[1:]

	}
	return errors.New(500, "USER_NOT_FOUND", fmt.Sprintf(format, args...)).WithReasonCode(1).WithErrStack()
}
