// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/jaggerzhuang1994/kratos-foundation-template/api/example_service/example_pb"
	"github.com/jaggerzhuang1994/kratos-foundation-template/internal/biz/example/user1"
	"github.com/jaggerzhuang1994/kratos-foundation-template/internal/biz/example/user2"
	"github.com/jaggerzhuang1994/kratos-foundation-template/internal/biz/example/user3"
	client2 "github.com/jaggerzhuang1994/kratos-foundation-template/internal/client"
	"github.com/jaggerzhuang1994/kratos-foundation-template/internal/conf"
	"github.com/jaggerzhuang1994/kratos-foundation-template/internal/data"
	"github.com/jaggerzhuang1994/kratos-foundation-template/internal/service"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/app_info"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/app"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/client"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/config"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/consul"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/database"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/job"
	config2 "github.com/jaggerzhuang1994/kratos-foundation/pkg/component/job/config"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/job/cron"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/job/otel"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/log"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/metrics"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/redis"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/registry"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/server"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/server/websocket"
	"github.com/jaggerzhuang1994/kratos-foundation/pkg/component/tracing"
)

import (
	_ "github.com/jaggerzhuang1994/kratos-foundation/pkg/setup"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(arg *app_info.AppInfo, fileConfigSource conf.FileConfigSource) (*kratos.App, func(), error) {
	v, err := consul.NewConsul()
	if err != nil {
		return nil, nil, err
	}
	configFileConfigSource, err := conf.NewFileSource(arg, fileConfigSource)
	if err != nil {
		return nil, nil, err
	}
	consulConfigSource := conf.NewConsulSource(arg)
	configConfig, cleanup, err := config.NewConfig(v, configFileConfigSource, consulConfigSource)
	if err != nil {
		return nil, nil, err
	}
	v2, err := server.NewConfig(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	register := server.NewRegister(v2)
	v3, err := log.NewConfig(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logLog, cleanup2, err := log.NewLog(v3, arg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v4, err := metrics.NewConfig(configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v5, err := metrics.NewMetrics(v4, arg, logLog)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v6, err := tracing.NewConfig(configConfig, arg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v7, cleanup3, err := tracing.NewTracing(v6, arg, logLog)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	defaultMiddleware := server.NewDefaultMiddleware(v2, logLog, v5, v7)
	hook := server.NewHook(defaultMiddleware)
	httpServer := server.NewHttpServer(v2, register, hook)
	grpcServer := server.NewGrpcServer(v2, register, hook)
	websocketHook := websocket.NewHook()
	websocketServer := websocket.NewServer(logLog, httpServer, websocketHook)
	v8, err := database.NewConfig(configConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	loggerInterface := database.NewGormLogger(logLog, v8)
	gormConfig := database.NewGormConfig(v8, loggerInterface)
	tracingPlugin := database.NewTracingPlugin(v8, v7)
	defaultConnection, err := database.NewDefaultConnection(v8)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dbResolver := database.NewDbResolver(v8)
	manager, err := database.NewManager(v8, logLog, gormConfig, tracingPlugin, defaultConnection, dbResolver)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userDbRepo := data.NewUserDbRepo(manager)
	user1Biz := user1.NewUser1Biz(userDbRepo)
	v9, err := redis.NewConfig(configConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisManager, cleanup4, err := redis.NewManager(logLog, v9, v7, v5)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userCacheRepo := data.NewUserCacheRepo(redisManager)
	user2Biz := user2.NewUser2Biz(userCacheRepo)
	v10, err := client.NewConfig(configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	consulRegistry := registry.NewConsulRegistry(v)
	discovery := registry.NewKratosDiscovery(consulRegistry)
	factory := client.NewFactory(v10, logLog, discovery, v7, v5)
	exampleServiceApiWrapper := example_pb.NewExampleServiceApiWrapper(factory)
	biz3GetUserImpl := client2.NewBiz3GetUserImpl(exampleServiceApiWrapper)
	bootstrap, err := conf.NewBootstrap(configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	user3Biz := user3.NewUser3Biz(biz3GetUserImpl, bootstrap)
	exampleService := service.NewExampleService(user1Biz, user2Biz, user3Biz)
	exampleWsHandler := service.NewExampleWsHandler()
	bootstrapBootstrap := NewBootstrap(httpServer, grpcServer, websocketServer, exampleService, exampleWsHandler)
	v11, err := app.NewConfig(configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appHook := app.NewHook(logLog)
	v12, err := config2.NewConfig(configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tracingProvider := otel.NewTracingProvider(v7, v12)
	metricsProvider, err := otel.NewMetricsProvider(v5, v12)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v13 := cron.NewScheduleParser()
	cronLogger := cron.NewCronLogger(logLog, v12)
	cronCron, err := cron.NewCron(logLog, v12, v13, cronLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobRegister := job.NewRegister(logLog, v12)
	jobServer, err := job.NewServer(v12, logLog, tracingProvider, metricsProvider, cronCron, v13, jobRegister)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registrar := registry.NewKratosRegistry(consulRegistry)
	kratosApp := app.NewApp(bootstrapBootstrap, httpServer, grpcServer, websocketServer, arg, v11, logLog, v5, appHook, jobServer, register, registrar)
	return kratosApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
